### ISSUE TITLE
CORS error on https://api.memegen.link/templates/ 

### ISSUE THREAD

**Issue by Josehower** [jacebrowning/memegen#687]
HI @jacebrowning,

Thank you for this API is amazing and we have been using it to teach React on our coding Bootcamp for some years now.

I found that some days ago trying to fetch the templates from https://api.memegen.link/templates/ is throwing a CORS error.

This is are the links to the app that used to work before 

Deployed: https://react-meme-scraper.netlify.app/

Repo: https://github.com/Josehower/React-meme-generator

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/61600906/154453997-78c450e2-8219-4210-8921-c047b77d1848.png">

Please let me know if this is intended. 

and thank you in advance for any help you can give me here.

Good energy 👍👍👍👍

**Comment by jacebrowning** [comment]
That mostly likely caused by https://github.com/jacebrowning/memegen/pull/678. I'll investigate...

**Comment by jacebrowning** [comment]
OK, this should be fixed by https://github.com/jacebrowning/memegen/commit/dfe7a9c3bfc4e2763a9c41982dd5d7986ad1d16f. Thanks for the report and let me know if that not working for you!

**Comment by Josehower** [comment]
@jacebrowning unfortunately the cors error is still happening.

I am going to try to send "no-cors" mode. But still, this may break a lot of projects using the last implementation.

**Comment by jacebrowning** [comment]
@Josehower is it possible something is cached on your end? This is what I see on your site:

![](https://cdn.zappy.app/de74688b023be5668cee30d58dec1336.png)

**Comment by ProchaLu** [comment]
@jacebrowning unfortunately the cors error is also happening for me
<img width="1436" alt="Screenshot 2022-02-17 at 17 36 03" src="https://user-images.githubusercontent.com/80746311/154528031-1ea4e3d2-d28c-4280-9c79-b9cc4fa42fc7.png">

**Comment by Josehower** [comment]
I cleaned the cache tried from incognito mode and used a different Browser, all of these environments throw me the CORS error.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61600906/154527553-49af7c87-85fb-4279-9d9c-f291de25406a.png">

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/61600906/154528178-952d0aae-42b2-4f52-a11d-523608cceef5.png">

I'll ask a colleague to check it out and let you know.

Again, thank you for your attention and quick response.

**Comment by jacebrowning** [comment]
Can one of you paste the values or share a screenshot of the Headers tab for the `templates` request?

**Comment by Josehower** [comment]
KK Just checked from my mac and now I got the right response.

thanks for your help. 🙌

**Comment by jacebrowning** [comment]
Good to know! It's possible there's still a misconfiguration (see https://github.com/sanic-org/sanic-ext/issues/62#issuecomment-1043359022) regarding `OPTIONS`) but I think it may have just taken a while for the cache to propagate.
